baseURL: https://noeblassel.github.io
languageCode: en-us
title: Noé Blassel's homepage
theme: gokarna
env: production
copyright: Noé Blassel 2022,
enableEmoji: true
outputs:
  home:
    - JSON
    - RSS
    - HTML
defaultContentLanguage: en
languages:
  en:
    languageName: ":us:"
    profileMode:
      enabled: true
      title: "Noé Blassel"
      subtitle: "PhD Student in Applied Mathematics / Computational Statistical Physics"
      imageURL: /photo.jpg
      imageWidth: 3971
      imageHeight: 3971
    menu:
      main:
        - name: About Me
          url: /about/
          weight: 1
        - name: Research
          url: /research/
          weight: 2
        - name: Teaching
          url: /teaching/
          weight: 3
        - name: Posts
          url: /posts/
          weight: 4

params:
  displayFullLangName: true
  name: Home
  disableSpecial1stPost: true
  ShowReadingTime: false
  ShowToc: false
  TocOpen: false
  ShowBreadCrumbs: false
  ShowPostNavLinks: true
  comments: true
  avatarURL: /photo.jpg
  avatarSize: size-xl 
  customHeadHTML: '<link rel="stylesheet" href="/css/custom.css">'
  socialIcons:
    - name: github
      url: https://github.com/noeblassel
    - name: email
      url: mailto:noe.blassel@enpc.fr
    - name: linkedin
      url: https://www.linkedin.com/in/noe-blassel-758085146/
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote: true
